from typing import List
from typing import Annotated
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field

class AgentState(BaseModel):
    """
    Represents the state of our graph.

    Attributes:
        messages: Chat history (automatically appended by LangGraph).
        question: The current user question.
        documents: List of retrieved or searched documents.
        generation: The final answer generated by the LLM.
        session_id: Unique ID to isolate user files.
        route: The decision made by the router (web_search/vectorstore).
        hallucination_grade: Result of the hallucination check (yes/no).
        loop_step: How many times we did loop.
    """
    messages: Annotated[list, add_messages] = Field(default_factory=list)
    question: str = Field(default="")
    documents: List[str] = Field(default_factory=list)
    generation: str = Field(default="")
    session_id: str = Field(default="")
    route: str = Field(default="")
    hallucination_grade: str = Field(default="")
    loop_step: int = Field(default=0)